Repository doodle-dev-avatar/doodle-dev-avatar-fe, pull requests merged in 2025-03, with the labels that each got.

#32 [#31] iOS, macOS에서 이미지 내보내기시 버그 수정
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/assets/background/background_diagonal.svg
  src/assets/background/background_dot.svg
  src/assets/background/background_grid.svg
  src/assets/background/background_linear.svg
  src/assets/background/background_radial.svg
  src/assets/background/background_white.svg
  src/components/common/Image/BackgroundImage.tsx
  src/components/constants/backgroundIconType.tsx
  src/components/constants/commentIconType.tsx
  src/components/constants/goodsIconType.tsx
  src/components/result/Comment.tsx
  src/hooks/useSaveImage.ts
Labels: refactor 🔧, bug 🚨

#33 [#30] feat: meta tag, favicon 설정
  src/app/icon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/thumbnail.png
  src/components/common/Image/MainIcon.tsx
Labels: feat ✨

#35 [#30] feat: meta tag, favicon 설정
  src/app/icon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/thumbnail.png
  src/components/common/Image/MainIcon.tsx
Labels: feat ✨

#36 Release 1.0.0
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/icon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/thumbnail.png
  src/assets/background/background_diagonal.svg
  src/assets/background/background_dot.svg
  src/assets/background/background_grid.svg
  src/assets/background/background_linear.svg
  src/assets/background/background_radial.svg
  src/assets/background/background_white.svg
  src/components/common/Image/BackgroundImage.tsx
  src/components/common/Image/MainIcon.tsx
  src/components/constants/backgroundIconType.tsx
  src/components/constants/commentIconType.tsx
  src/components/constants/goodsIconType.tsx
  src/components/result/Comment.tsx
  src/hooks/useSaveImage.ts
Labels: deploy 🚀
